name: mobile_ideal_project
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  auto_route: 8.0.0
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  laravel_exception: ^0.0.4
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^10.0.1
  easy_localization: ^3.0.7
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  lottie: ^3.1.2
  easy_logger: ^0.0.2
  intl: ^0.19.0
  equatable: ^2.0.5
  video_player: ^2.8.7
  chewie: ^1.8.1
  video_thumbnail: ^0.5.3
  cached_network_image: ^3.3.1
  photo_manager: ^3.2.0
  photo_manager_image_provider: ^2.1.1
  linkify: ^5.0.0
  any_link_preview: ^3.0.2
  flutter_linkify: ^6.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  riverpod_lint: ^2.3.10
  easy_localization_loader: ^2.0.2
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.5.0+1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/translations/
    - assets/svgs/
    - assets/fonts/

  fonts:
    # Raleway
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300

    # Cairo
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300

flutter_gen:
  output: lib/generated
  integrations:
    flutter_svg: true
